# fly.toml app configuration file generated for karlsruhe-garbage-calendar on 2023-06-16T21:16:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "karlsruhe-garbage-calendar"
primary_region = "cdg"

[build]
  dockerfile = ".docker/deploy.dockerfile"

[http_service]
  internal_port = 8008
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
